### ISSUE TITLE
How it works, the implementation

### ISSUE THREAD

**Issue by suntong** [siongui/gojianfan#1]
Hi, 

I'm wondering how does the program works -- Is the mapping all defined in the https://github.com/siongui/gojianfan/blob/master/charsets.go file? That doesn't look to me to contain the whole UTF8 Chinese characters to me though. 

What I'm missing? Thx.

**Comment by siongui** [comment]
Yes, the mapping is all defined in the charsets.go.
I am not sure whether it contains whole UTF8 Chinese chars or not. The mapping comes from another unmaintained project. This is simple and naive solution and enough for me. I do not like to use opencc because you need to compile the C/C++ code or install the packages, which sometimes breaks the build of my projects.

If you need complete or better solution, please use OpenCC.

**Comment by suntong** [comment]
Yeah, I saw that (about OpenCC) in your readme, but I only need the simplest approach like yours. 

Have you done any coverage test on the table anyhow?

**Comment by siongui** [comment]
No, I just port the code from Python to Go.

I am not an expert in Chinese char mapping. If you are, please help write test case.

If you are writing code for a serious commercial project, I suggest you do NOT use this package.

**Comment by suntong** [comment]
No, I'm not writing any serious commercial projects, but why suggesting NOT to use this package? What's your concern? 

OK. I'll try to do some coverage test then, and see how well that Python table is...

**Comment by siongui** [comment]
Because I do not know whether the mapping is correct or not.

If you are building a serious commercial product and the conversion is not correct, you may be fired. Please use at your caution.

**Comment by suntong** [comment]
Thanks. I'll close it for now.

**Comment by suntong** [comment]
Found the answer. There are actually 2473 Chinese-Character that need to be converted between Simplified and Traditional, but that table only contains 2359 pairs. 

I'll put the table and Go code in 
https://github.com/go-cc/cc-table/tree/master/cc-jianfan
in a few days.

**Comment by suntong** [comment]
Ref: https://play.golang.org/p/ei7PnqkOQH

**Comment by siongui** [comment]
The difficulty is there is no 1-1 mapping. One simplified char may be mapped to one or more traditional char.

But the mapping in current code is 1-1 mapping, which is obvious wrong. Why don't you just use the table of OpenCC?

**Comment by suntong** [comment]
Hmm, yeah, that's a good advice. Thx.

**Comment by suntong** [comment]
FTR, the [go-cc/cc-jianfan](https://github.com/go-cc/cc-jianfan) is now using the full table from OpenCC. I.e., every case in OpenCC dictionary is now covered in [go-cc/cc-jianfan](https://github.com/go-cc/cc-jianfan).

**Comment by siongui** [comment]
Looks good to me. Not sure what is you job. I am looking for short-term small coding case (Go/Python/JavaScript/HTML/CSS). If you are interested, please mail me.

**Comment by suntong** [comment]
Not currently as I've committed to [rewriting the pinyin lib](https://github.com/mozillazg/go-pinyin/issues/26). 
Thanks for the offer, will reach out to you afterwards.

**Comment by siongui** [comment]
If you can pay me, I believe I am the right person to help you rewrite the pinyin lib. If you are interested, mail me and we discuss in the mail.

**Comment by suntong** [comment]
Actually no, I'm not behind any big corporation. I'm doing it totally on my own, using the free time apart from my day job.
